name: Frontend CI

on:
  push:
    branches: [main, dev]
    paths:
      - "front/**"
      - ".github/workflows/frontend.yml"
  pull_request:
    branches: [main, dev]
    paths:
      - "front/**"
      - ".github/workflows/frontend.yml"
  workflow_dispatch:

jobs:
  docker:
    name: Build & Deploy frontend (Cloud Run)
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - id: gcp-auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev --quiet

      - name: Build and push
        run: |
          IMAGE=europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/tp-cloud/frontend:${{ github.sha }}
          docker build -t $IMAGE ./front
          docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy cloud-frontend \
            --image europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/tp-cloud/frontend:${{ github.sha }} \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --set-env-vars CORE_URL=${{ secrets.CORE_URL }},AUTH_URL=${{ secrets.AUTH_URL }}
